# Generated by Django 5.2.4 on 2025-10-27 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='highlight_1_text',
            field=models.CharField(blank=True, default='Excellence in Education', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='highlight_2_text',
            field=models.CharField(blank=True, default='Industry Partnerships', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='highlight_3_text',
            field=models.CharField(blank=True, default='Research Impact', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='overlay_opacity',
            field=models.FloatField(default=0.4, help_text='Overlay opacity from 0.0 to 1.0'),
        ),
        migrations.AddField(
            model_name='banner',
            name='show_highlights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='awards',
            field=models.TextField(blank=True, help_text='Awards and recognitions (JSON format)'),
        ),
        migrations.AddField(
            model_name='team',
            name='education',
            field=models.TextField(blank=True, help_text='Educational background (JSON format)'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_on_study_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='publications_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='research_areas',
            field=models.TextField(blank=True, help_text='Research areas (JSON format)'),
        ),
        migrations.AddField(
            model_name='team',
            name='title',
            field=models.CharField(blank=True, help_text='Official title or designation', max_length=200),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='key_faculty',
            field=models.ManyToManyField(blank=True, related_name='research_area_memberships', to='csmz.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(choices=[('head', 'Head of Department'), ('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('senior_lecturer', 'Senior Lecturer'), ('lecturer', 'Lecturer'), ('assistant_lecturer', 'Assistant Lecturer'), ('tutorial_assistant', 'Tutorial Assistant'), ('admin', 'Administrative Staff'), ('technical', 'Technical Staff')], max_length=50),
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
            },
        ),
    ]
