# Generated by Django 5.2.4 on 2025-10-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmz', '0002_banner_highlight_1_text_banner_highlight_2_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='publications_count',
        ),
        migrations.AddField(
            model_name='banner',
            name='highlight_1_icon',
            field=models.ImageField(blank=True, help_text='Icon for highlight 1 (PNG or SVG)', null=True, upload_to='banner_icons/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='highlight_2_icon',
            field=models.ImageField(blank=True, help_text='Icon for highlight 2 (PNG or SVG)', null=True, upload_to='banner_icons/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='highlight_3_icon',
            field=models.ImageField(blank=True, help_text='Icon for highlight 3 (PNG or SVG)', null=True, upload_to='banner_icons/'),
        ),
        migrations.AddField(
            model_name='team',
            name='publications',
            field=models.TextField(blank=True, help_text='Publications with HTML formatting (supports <br> and <a> tags)'),
        ),
    ]
