# Generated by Django 5.2.4 on 2025-10-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmz', '0002_auto_20251021_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
