# Generated by Django 5.2.4 on 2025-10-27 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csmz', '0003_add_banner_icons_and_publications_html'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
