# Generated by Django 5.2.4 on 2025-07-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmz', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='default_news_image', upload_to='news_images/'),
        ),
    ]
