# Generated by Django 5.2.4 on 2025-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmz', '0004_delete_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(default='Computer Systems & Mathematics', max_length=200)),
                ('university_name', models.CharField(default='Ardhi University', max_length=200)),
                ('physical_address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, help_text='General contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='General contact phone', max_length=50)),
                ('contact_fax', models.CharField(blank=True, max_length=50)),
                ('footer_caption', models.TextField(blank=True, default='© 2024 CSM Department. All rights reserved.', help_text='Text displayed in footer caption')),
                ('footer_bottom_text', models.TextField(blank=True, default='Designed and developed for Computer Systems & Mathematics Department', help_text='Footer bottom text/caption')),
                ('hod_message_title', models.CharField(blank=True, default='Welcome Message', max_length=200)),
                ('hod_message_content', models.TextField(blank=True)),
                ('hod_photo', models.ImageField(blank=True, null=True, upload_to='hod_photos/')),
                ('hod_name', models.CharField(blank=True, default='Head of Department', max_length=200)),
                ('hod_title', models.CharField(blank=True, max_length=200)),
                ('site_description', models.TextField(blank=True)),
                ('site_keywords', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('event', 'Event'), ('research', 'Research Update'), ('student_achievement', 'Student Achievement'), ('faculty_news', 'Faculty News'), ('department_news', 'Department News'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
