# Generated by Django 5.2.4 on 2025-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csmz', '0004_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('news', 'News')], default='event', max_length=100),
        ),
    ]
