# Generated by Django 5.2.4 on 2025-08-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csmz', '0005_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
    ]
